### ISSUE TITLE
Clarification on "inspiration" in the Download section of README

### ISSUE THREAD

**Issue by yongsubaek** [SelfishGene/SFHQ-dataset#6]
Hi, Could you please provide more information on the meaning of "inspiration" mentioned in the Download section of the README file?

---
The dataset can be downloaded via kaggle:

[Part 1](https://www.kaggle.com/datasets/selfishgene/synthetic-faces-high-quality-sfhq-part-1) consists of 89,785 HQ 1024x1024 curated face images. It uses "inspiration" images from [Artstation-Artistic-face-HQ dataset (AAHQ)](https://github.com/onion-liu/aahq-dataset), [Close-Up Humans dataset](https://opensynthetics.com/dataset/close-up-humans-dataset-by-synthesis-ai/) and [UIBVFED dataset](http://ugivia.uib.es/uibvfed/).
[Part 2](https://www.kaggle.com/datasets/selfishgene/synthetic-faces-high-quality-sfhq-part-2) consists of 91,361 HQ 1024x1024 curated face images. It uses "inspiration" images from [Face Synthetics dataset](https://github.com/microsoft/FaceSynthetics) and by sampling from the [Stable Diffusion v1.4](https://github.com/CompVis/stable-diffusion) text to image generator using varied face portrait prompts.
[Part 3](https://www.kaggle.com/datasets/selfishgene/synthetic-faces-high-quality-sfhq-part-3) consists of 118,358 HQ 1024x1024 curated face images. It uses "inspiration" images by sampling from [StyleGAN2](https://github.com/NVlabs/stylegan2-ada-pytorch) mapping network with very high truncation psi coefficients to increase diversity of the generation. Here, the [e4e](https://github.com/omertov/encoder4editing) encoder is basically used a new kind of truncation trick.
[Part 4](https://www.kaggle.com/datasets/selfishgene/synthetic-faces-high-quality-sfhq-part-4) consists of 125,754 HQ 1024x1024 curated face images. It uses "inspiration" images by sampling from the [Stable Diffusion v2.1](https://github.com/Stability-AI/stablediffusion) text to image generator using varied face portrait prompts.

**Comment by SelfishGene** [comment]
What further information are you seeking?
You can find all detailes in the readme:

snippet from https://github.com/SelfishGene/SFHQ-dataset#synthetic-faces-high-quality-sfhq-dataset:

  It was created by "bringing to life" and turning to photorealistic face images from multiple "inspiration" sources (paintings, drawings, 3D models, text to image generators, etc) using a process similar to what is described [in this short twitter thread](https://twitter.com/DavidBeniaguev/status/1376020024511627273?s=20&t=kH9J5mV9hL8e3y8PruuB5Q). The process involves encoding the images into StyleGAN2 latent space and performing a small manipulation that turns each image into a photo-realistic image. These resulting candidate images are then further curated using a semi-manual semi-automatic process with the help of the lightweight [visual taste aprroximator](https://github.com/SelfishGene/visual_taste_approximator) tool

snippet from https://github.com/SelfishGene/SFHQ-dataset#more-details-about-dataset-generation-and-collection:

  The original inspiration images are taken from:
  - [Artstation-Artistic-face-HQ Dataset (AAHQ)](https://github.com/onion-liu/aahq-dataset) which contains mainly painting, drawing and 3D models of faces (part 1)
  - [Close-Up Humans Dataset](https://opensynthetics.com/dataset/close-up-humans-dataset-by-synthesis-ai/) that contains 3D models of faces (part 1)
  - [UIBVFED Dataset](http://ugivia.uib.es/uibvfed/) that also contain 3D models of faces (part 1)
  - [Face Synthetics Dataset](https://github.com/microsoft/FaceSynthetics) which contains 3D models of faces (part 2)
  - generated images using [stable diffusion v1.4 model](https://github.com/CompVis/stable-diffusion) using various face portrait prompts that span a wide range of ethnicities, ages, expressions, hairstyles, etc. (part 2)
  - StyleGAN2 mapping network sampled with larger that 1 truncation psi values, and then using a new truncation trick in which instead of moving towards the average w_avg vector, we move towards the encoded w_e4e vector to correct the example. illustation is provided in the section below (part 3)
  - generated images using [stable diffusion v2.1 model](https://github.com/Stability-AI/stablediffusion) using various face portrait prompts that span a wide range of ethnicities, ages, expressions, hairstyles, etc. (part 4)

**Comment by yongsubaek** [comment]
Thank you for your response.

Apologies for my vague initial question. 😅 
I'm trying to understand whether the term "inspiration" refers only to the non-photographic source datasets (paintings, drawings, 3D models, text to image generators) that you have mentioned, or if this term carries any specific restrictions, categories, or other meanings related to the usage of the dataset.

**Comment by SelfishGene** [comment]
The term refers to the source datasets to allow anyone to better understand the contents of the dataset and help reproduce it or expand it as they wish.
The dataset has no restrictions. You can you use it as you see fit.
